#cloud-config

users:
- name: composer
  uid: 2000
  groups: docker
write_files:
- path: /var/lib/docker/daemon.json
  permissions: 0644
  owner: root
  content: |
    {
      "live-restore": true,
      "storage-driver": "overlay2",
      "log-opts": {
        "max-size": "1024m"
      }
    }
- path: /home/composer/init.sh
  permissions: 0755
  owner: composer
  content: |
    TOKEN=$(curl -s -H "Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token)
    ACCESS=$(echo $${TOKEN} | grep --extended-regexp --only-matching "(ya29.[0-9a-zA-Z._-]*)")
    /usr/bin/docker login -u oauth2accesstoken -p "$${ACCESS}" https://gcr.io
    if [ ! -d /home/composer/opencspm ]; then
      cd /home/composer
      n=0
      until [ $n -ge 5 ]
      do
         git clone https://github.com/OpenCSPM/opencspm.git && break
         n=$[$n+1]
         sleep 5
      done

      mkdir -p /home/composer/opencspm/config
    cat << EOF > /home/composer/opencspm/config/config.yaml
    ---
    db:
      host: redis
      port: 6379
    buckets:
      - gs://${collection_bucket}
    EOF

    fi
    mkdir -p /home/composer/opencspm-controls
    if [ ! -d /home/composer/opencspm-controls/opencspm-darkbit-community-controls ]; then
      cd /home/composer/opencspm-controls
      n=0
      until [ $n -ge 5 ]
      do
         git clone https://github.com/OpenCSPM/opencspm-darkbit-community-controls.git && break
         n=$[$n+1]
         sleep 5
      done
    fi
- path: /etc/systemd/system/composer.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=Composer Service
    Requires=docker.service network-online.target
    After=docker.service network-online.target
    [Service]
    User=composer
    Environment="HOME=/home/composer"
    ExecStartPre=sh /home/composer/init.sh
    ExecStart=/usr/bin/docker run --rm -v  /var/run/docker.sock:/var/run/docker.sock -v "/home/composer/.docker:/root/.docker" -v "/home/composer:/home/composer" -w="/home/composer/opencspm/docker" docker/compose:1.27.4 up
    ExecStop=/usr/bin/docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v "/home/composer/.docker:/root/.docker" -v "/home/composer:/home/composer" -w="/home/composer/opencspom/docker" docker/compose:1.27.4 rm -f
    Restart=on-failure
    RestartSec=10
    TimeoutSec=600
    [Install]
    WantedBy=multi-user.target
runcmd:
- systemctl daemon-reload
- systemctl enable --now --no-block composer.service
- echo "success" > /etc/bootstrapped-by-tf
